using coretex_finalproj.Data;
using coretex_finalproj.Models;
using coretex_finalproj.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace coretex_finalproj.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly NotificationService _notificationService;
        private readonly AnalyticsService _analytics;

        public ReportController(ApplicationDbContext context, NotificationService notificationService, AnalyticsService analytics)
        {
            _context = context;
            _notificationService = notificationService;
            _analytics = analytics;
        }

        // --- Live Action Endpoints ---

        [HttpPost]
        public async Task<IActionResult> TriggerAlertEmail(string emailAddress, string alertType = "THRESHOLD_BREACH")
        {
            var message = alertType == "THRESHOLD_BREACH"
                ? "Sales Revenue has fallen below targets. Immediate review required."
                : "Manual system connectivity test successful.";

            try 
            {
                bool success = await _notificationService.SendExecutiveAlertEmailAsync(emailAddress, "System Performance Alert", message);
                if (success) return Json(new { success = true, message = "Alert Dispatched Successfully. Check your inbox (and Spam folder)." });
                return Json(new { success = false, message = "Server accepted request but dispatch failed. Verify your SendGrid Sender Identity." });
            }
            catch (System.Exception ex)
            {
                return Json(new { success = false, message = $"Infrastructure Error: {ex.Message}" });
            }
        }

        [HttpPost]
        public async Task<IActionResult> GenerateExecutiveReport(string emailAddress)
        {
            // 1. Gather Real Data via AnalyticsService
            var kpi = await _analytics.GetDashboardSnapshotAsync();

            // 2. Build Report Content (HTML)
            var content = $@"
                <div style='font-family: sans-serif; padding: 20px; color: #333;'>
                    <h2 style='color: #1e293b;'>Coretex Executive Monthly Report</h2>
                    <hr/>
                    <div style='display: grid; grid-template-columns: 1fr 1fr; gap: 20px;'>
                        <div style='background: #f8fafc; padding: 15px; border-radius: 8px;'>
                            <p style='font-size: 12px; color: #64748b; margin: 0;'>TOTAL REVENUE</p>
                            <p style='font-size: 24px; font-weight: bold; margin: 5px 0;'>PHP {kpi.TotalRevenue:N2}</p>
                        </div>
                        <div style='background: #f8fafc; padding: 15px; border-radius: 8px;'>
                            <p style='font-size: 12px; color: #64748b; margin: 0;'>NET PROFIT</p>
                            <p style='font-size: 24px; font-weight: bold; color: #10b981; margin: 5px 0;'>PHP {kpi.NetProfit:N2}</p>
                        </div>
                    </div>
                    <p style='margin-top: 20px;'>The business health score is currently <strong>{kpi.RiskLevel}</strong>.</p>
                    <p>Generated by Coretex Automated Reporting Engine.</p>
                </div>";

            // 3. Save to Database
            var reportRecord = new GeneratedReport
            {
                Title = "Monthly Executive Summary",
                PeriodLabel = "Current Month",
                ReportHtml = content,
                SentToEmail = emailAddress,
                SummaryData = $"Revenue: {kpi.TotalRevenue}, Profit: {kpi.NetProfit}"
            };

            _context.GeneratedReports.Add(reportRecord);
            await _context.SaveChangesAsync();

            // 4. Send Email
            bool emailSuccess = await _notificationService.SendExecutiveReportEmailAsync(emailAddress, "Your Monthly Executive Report", content);

            return emailSuccess ? Ok() : StatusCode(500);
        }

        // --- Navigation Views ---

        public async Task<IActionResult> History()
        {
            var reports = await _context.GeneratedReports
                .OrderByDescending(r => r.GeneratedAt)
                .ToListAsync();
            return View(reports);
        }

        public async Task<IActionResult> ViewReport(int id)
        {
            var report = await _context.GeneratedReports.FindAsync(id);
            if (report == null) return NotFound();
            return View(report);
        }
        [HttpGet]
        public async Task<IActionResult> ExportReportCsv()
        {
            var data = await _analytics.GetDashboardSnapshotAsync();
            var csv = "Metric,Value\n" +
                      $"Total Revenue,{data.TotalRevenue}\n" +
                      $"Total Expenses,{data.TotalExpenses}\n" +
                      $"Net Profit,{data.NetProfit}\n" +
                      $"Risk Level,{data.RiskLevel}\n" +
                      $"Generated At,{DateTime.Now}";

            var bytes = System.Text.Encoding.UTF8.GetBytes(csv);
            return File(bytes, "text/csv", $"CoretexReport_{DateTime.Now:yyyyMMdd}.csv");
        }
    }
}
