using coretex_finalproj.Data;
using coretex_finalproj.Models;
using coretex_finalproj.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace coretex_finalproj.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly NotificationService _notificationService;
        private readonly AnalyticsService _analytics;
        private readonly AuditLoggingService _auditLog;

        public ReportController(ApplicationDbContext context, NotificationService notificationService, AnalyticsService analytics, AuditLoggingService auditLog)
        {
            _context = context;
            _notificationService = notificationService;
            _analytics = analytics;
            _auditLog = auditLog;
        }

        // --- Live Action Endpoints ---

        [HttpPost]
        public async Task<IActionResult> TriggerAlertEmail(string emailAddress, string alertType = "THRESHOLD_BREACH")
        {
            var message = alertType == "THRESHOLD_BREACH"
                ? "Sales Revenue has fallen below targets. Immediate review required."
                : "Manual system connectivity test successful.";

            try 
            {
                bool success = await _notificationService.SendExecutiveAlertEmailAsync(emailAddress, "System Performance Alert", message);
                if (success) return Json(new { success = true, message = "Alert Dispatched Successfully. Check your inbox (and Spam folder)." });
                return Json(new { success = false, message = "Server accepted request but dispatch failed. Verify your SendGrid Sender Identity." });
            }
            catch (System.Exception ex)
            {
                return Json(new { success = false, message = $"Infrastructure Error: {ex.Message}" });
            }
        }

        [HttpPost]
        public async Task<IActionResult> GenerateExecutiveReport(string emailAddress)
        {
            // 1. Gather Real Data via AnalyticsService
            var kpi = await _analytics.GetDashboardSnapshotAsync();

            // 2. Build Report Content (HTML)
            var content = $@"
                <div style='font-family: sans-serif; padding: 20px; color: #333;'>
                    <h2 style='color: #1e293b;'>Coretex Executive Monthly Report</h2>
                    <hr/>
                    <div style='display: grid; grid-template-columns: 1fr 1fr; gap: 20px;'>
                        <div style='background: #f8fafc; padding: 15px; border-radius: 8px;'>
                            <p style='font-size: 12px; color: #64748b; margin: 0;'>TOTAL REVENUE</p>
                            <p style='font-size: 24px; font-weight: bold; margin: 5px 0;'>PHP {kpi.TotalRevenue:N2}</p>
                        </div>
                        <div style='background: #f8fafc; padding: 15px; border-radius: 8px;'>
                            <p style='font-size: 12px; color: #64748b; margin: 0;'>NET PROFIT</p>
                            <p style='font-size: 24px; font-weight: bold; color: #10b981; margin: 5px 0;'>PHP {kpi.NetProfit:N2}</p>
                        </div>
                    </div>
                    <p style='margin-top: 20px;'>The business health score is currently <strong>{kpi.RiskLevel}</strong>.</p>
                    <p>Generated by Coretex Automated Reporting Engine.</p>
                </div>";

            // 3. Save to Database
            var reportRecord = new GeneratedReport
            {
                Title = "Monthly Executive Summary",
                PeriodLabel = "Current Month",
                ReportHtml = content,
                SentToEmail = emailAddress,
                SummaryData = $"Revenue: {kpi.TotalRevenue}, Profit: {kpi.NetProfit}"
            };

            _context.GeneratedReports.Add(reportRecord);
            await _context.SaveChangesAsync();

            // 4. Send Email
            bool emailSuccess = await _notificationService.SendExecutiveReportEmailAsync(emailAddress, "Your Monthly Executive Report", content);
            
            await _auditLog.LogActivityAsync("REPORT_GENERATE", $"Generated executive monthly report for {emailAddress}");

            return emailSuccess ? Ok() : StatusCode(500);
        }

        // --- Navigation Views ---

        public async Task<IActionResult> History()
        {
            var reports = await _context.GeneratedReports
                .OrderByDescending(r => r.GeneratedAt)
                .ToListAsync();
            return View(reports);
        }

        public async Task<IActionResult> ViewReport(int id)
        {
            var report = await _context.GeneratedReports.FindAsync(id);
            if (report == null) return NotFound();
            return View(report);
        }
        [HttpGet]
        public async Task<IActionResult> ExportReportCsv()
        {
            var globalData = await _analytics.GetDashboardSnapshotAsync();
            var branchPerformance = await _context.Branches
                .Where(b => !b.IsArchived)
                .Select(b => new {
                    Name = b.Name,
                    Revenue = _context.Sales.Where(s => s.BranchId == b.Id && !s.IsArchived).Sum(s => s.Amount),
                    Expenses = _context.Expenses.Where(e => e.BranchId == b.Id && !e.IsArchived).Sum(e => e.Amount)
                })
                .ToListAsync();

            var sortedBranches = branchPerformance
                .OrderByDescending(b => b.Revenue - b.Expenses)
                .ToList();

            var csv = new System.Text.StringBuilder();
            csv.AppendLine("CORETEX EXECUTIVE BRANCH PERFORMANCE REPORT");
            csv.AppendLine($"Generated At,{DateTime.Now:f}");
            csv.AppendLine($"Global Risk Level,{globalData.RiskLevel}");
            csv.AppendLine();
            csv.AppendLine("Rank,Branch Name,Revenue (PHP),Expenses (PHP),Net Profit (PHP)");

            for (int i = 0; i < sortedBranches.Count; i++)
            {
                var b = sortedBranches[i];
                var profit = b.Revenue - b.Expenses;
                csv.AppendLine($"{i + 1},{b.Name},{b.Revenue:F2},{b.Expenses:F2},{profit:F2}");
            }

            csv.AppendLine();
            csv.AppendLine($"TOTAL,,{globalData.TotalRevenue:F2},{globalData.TotalExpenses:F2},{globalData.NetProfit:F2}");

            var bytes = System.Text.Encoding.UTF8.GetBytes(csv.ToString());
            await _auditLog.LogActivityAsync("REPORT_EXPORT", "Exported professional branch performance report to CSV");
            return File(bytes, "text/csv", $"Coretex_BranchRanking_{DateTime.Now:yyyyMMdd}.csv");
        }
    }
}
